version: "3.8"
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: ./php-apache2
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./source/:/var/www/html/
    ports:
      - 8088:80

  db:
    container_name: db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: dfz
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3308:3306"
    volumes:
      - ./sources/data/data.sql:/docker-entrypoint-initdb.d/dump.sql
    user: mysql
